### ISSUE TITLE
Gradle build error with cats-core

### ISSUE THREAD

**Issue by porl** [Kotori316/SLP-example#1]
After a git clone and immediate ./gradlew build:

I get the error message:

====

Project evaluation failed including an error in afterEvaluate {}. Run with --stacktrace for details of the afterEvaluate {} error.

FAILURE: Build failed with an exception.

* Where:
Build file '/home/porl/workspace/minecraftmods/1.15.2/SLP-example/build.gradle' line: 93

* What went wrong:
A problem occurred evaluating root project 'SLP-example'.
> Could not find method implementation() for arguments [{group=org.typelevel, name=cats-core_2.13, version=2.1.0}] on repository container of type org.gradle.api.internal.artifacts.dsl.DefaultRepositoryHandler.

====

Do I need to do anything else before calling the build task?

**Comment by Kotori316** [comment]
I mistook the place to write `implementation()`. If you don't need [Cats](https://mvnrepository.com/artifact/org.typelevel/cats-core_2.13/2.1.0), just remove 93rd line.
